### PR TITLE
Fix showing both real and symlink image from different directories

### PR DESCRIPTION
**Pull request by karlch**
The new usage of realpath introduced in 0cc236327662dbf18c5f1d82cee287941d4e1350 also introduced a new bug. The image filelist would load both the symlink and the original image, even if they are not in the same directory. This PR attempts to save this issue while also fixing the initial issue that the mentioned commit tried to address.

Related to #374

### CODE REVIEW

**Comment by jcjgraf** [comment]
I can confirm that the newly introduced bug is fixed.

**Comment by jcjgraf** [comment]
I could not reproduce the first problem described in #374, but I am not sure about the initial one. @BachoSeven could you maybe give it a try?

**Comment by BachoSeven** [comment]
Hei, I tried to reproduce what I mentioned(i.e. [this](https://github.com/karlch/vimiv-qt/issues/374#issuecomment-827932686)), and it indeed does seem fixed, meaning entering that directory within the symlink(which itself then contains symlinks) (with vimiv from this branch) doesn't crash anymore.

**Comment by BachoSeven** [comment]
If this is merged, it fixes  #374.

**Comment by jcjgraf** [comment]
>  I hoped this would do the github thingie where it automagically closes the issue once the PR gets merged :'D

This only works if added to the PR description or to a commit message in this PR I guess

**Comment by karlch** [comment]
Wow, been a while, shame on me but time to merge :smile:

**Comment by jcjgraf** [comment]
Awesome, thanks for fixing and merging. This way I do not always have to checkout this branch when using Vimiv :blush:

**Pull request merged**
