### PR TITLE
Go headerless

### LINKED ISSUE #667: Simplify Copyrights
It would make our life easier if we simplified the copyrights all over the place.

Code files I would use something along:
```
# Copyright: the vimiv contributors, licensed under the GNU GPL v3
# See the "AUTHORS" and "LICENSE" files for details
```

And then also use "the vimiv contributors" instead of "2017-2023, Christian Karl" for the sphinx-generated documents (website, man page).

This fulfils two purposes:
1. Remove the tedious bookkeeping of the years
2. Have all authors part of the copyright, not just me :smile: especially useful in case we move towards a vimiv organisation for v1.0.0.

### PR DESCRIPTION
**Pull request by karlch**
@jcjgraf and @buzzingwires would you mind giving the wording in the AUTHORS file a quick check?

fixes #667

EDIT: still a few other (sphinx-related) places referring to me explicitly in copyright.

- [x] website
- [x] man page

### CODE REVIEW

**Comment by jcjgraf** [comment]
I like the simplification of the header a lot.

Your proposition looks good. I would extend it a bit to something like:

```
Vimiv was conceived of and written by Christian Karl (karlch).

Copyright: the vimiv contributors, licensed under the GNU GPL v3.
See https://www.gnu.org/licenses/gpl-3.0.html or LICENCE file.

All contributors of non-trivial code are listed here, in order of first contribution:

Christian Karl (karlch) <karlch at protonmail dot com>
Wolfgang Popp (woefe) <mail at wolfgang-popp dot de>
Ankur Sinha (sanjayankur31) <ankursinha at fedoraproject dot org>
Jean-Claude Graf (jcjgraf) <jeanggi90 at gmail dot com>
Mateus Etto (Yutsuten) <mateus dot etto at gmail dot com>
buzzingwires (buzzingwires) <buzzingwires at outlook dot com>
```

**Comment by karlch** [comment]
Thanks for the idea, I really like it and adapted the AUTHORS file, slightly updating the wording :blush:

**Comment by jcjgraf** [comment]
This is looking good to me :+1:

**Comment by buzzingwires** [comment]
Sorry for the slow response. It looks good to me! I think it straightforwardly lays out the information as discussed in #667

**Pull request merged**
